# Generated by Django 3.2.4 on 2021-06-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('forward', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('lat', models.FloatField(max_length=8)),
                ('lon', models.FloatField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='StopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stop')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='bus_stops',
            field=models.ManyToManyField(related_name='bus_stops', through='api.StopInfo', to='api.Stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='end_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='api.stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='api.stop'),
        ),
    ]
