# Generated by Django 3.2.4 on 2021-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='first_stripe',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='last_stripe',
            field=models.CharField(default=' ', max_length=9),
            preserve_default=False,
        ),
    ]
