# Generated by Django 3.2.4 on 2021-06-12 12:15

import api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210612_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='first_stripe',
            field=models.CharField(choices=[('#FFFFFF', 'WHITE'), ('#000000', 'BLACK'), ('#E53935', 'RED'), ('#4FC3F7', 'LIGHT_BLUE'), ('#1E88E5', 'BLUE'), ('#01579B', 'DARK_BLUE'), ('#4CAF50', 'GREEN'), ('#1B5E20', 'DEEP_GREEN'), ('#FDD835', 'YELLOW')], default=api.enums.RouteColors['WHITE'], max_length=9),
        ),
        migrations.AlterField(
            model_name='route',
            name='last_stripe',
            field=models.CharField(choices=[('#FFFFFF', 'WHITE'), ('#000000', 'BLACK'), ('#E53935', 'RED'), ('#4FC3F7', 'LIGHT_BLUE'), ('#1E88E5', 'BLUE'), ('#01579B', 'DARK_BLUE'), ('#4CAF50', 'GREEN'), ('#1B5E20', 'DEEP_GREEN'), ('#FDD835', 'YELLOW')], default=api.enums.RouteColors['WHITE'], max_length=9),
        ),
    ]
