# Generated by Django 3.2.4 on 2021-06-16 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210612_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(max_length=5)),
                ('final_stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_stop', to='api.stop')),
                ('mid_stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mid_stop', to='api.stop')),
            ],
        ),
        migrations.CreateModel(
            name='StopNotifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('Journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.journey')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stop')),
            ],
        ),
        migrations.CreateModel(
            name='RouteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.journey')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='notify_stops',
            field=models.ManyToManyField(related_name='notify_stops', through='api.StopNotifyOrder', to='api.Stop'),
        ),
        migrations.AddField(
            model_name='journey',
            name='routes',
            field=models.ManyToManyField(through='api.RouteOrder', to='api.Route'),
        ),
        migrations.AddField(
            model_name='journey',
            name='start_stop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_stop', to='api.stop'),
        ),
    ]
