# Generated by Django 3.2.4 on 2021-06-16 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210616_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='final_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_stop', to='api.stop'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='mid_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mid_stop', to='api.stop'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_stop', to='api.stop'),
        ),
    ]
