# Generated by Django 3.2.4 on 2021-06-16 03:29

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210616_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='routing_stops',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='routing_stops', to='api.Stop'),
        ),
    ]
