# Generated by Django 3.2.4 on 2021-06-16 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_journey_routing_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2021, 6, 16, 3, 36, 34, 246424, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
