# Generated by Django 3.2.4 on 2021-06-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_journey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
