# Generated by Django 3.2.4 on 2021-07-01 09:17

import api.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210626_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='mid_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid_stop', to='api.stop'),
        ),
        migrations.AlterField(
            model_name='route',
            name='first_stripe',
            field=models.CharField(choices=[('#EEEEEE', 'WHITE'), ('#9E9E9E', 'BLACK'), ('#EF5350', 'RED'), ('#00BCD4', 'BLUE'), ('#9CCC65', 'GREEN'), ('#1B5E20', 'DEEP_GREEN'), ('#FDD835', 'YELLOW')], default=api.enums.RouteColors['WHITE'], max_length=9),
        ),
        migrations.AlterField(
            model_name='route',
            name='last_stripe',
            field=models.CharField(choices=[('#EEEEEE', 'WHITE'), ('#9E9E9E', 'BLACK'), ('#EF5350', 'RED'), ('#00BCD4', 'BLUE'), ('#9CCC65', 'GREEN'), ('#1B5E20', 'DEEP_GREEN'), ('#FDD835', 'YELLOW')], default=api.enums.RouteColors['WHITE'], max_length=9),
        ),
    ]
