# Generated by Django 3.2.4 on 2021-07-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210701_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='route',
            field=models.TextField(default=''),
        ),
    ]
