# Generated by Django 3.2.4 on 2021-07-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_journey_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='route',
            field=models.TextField(default=''),
        ),
    ]
