# Generated by Django 3.2.4 on 2021-07-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_journey_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='route',
            new_name='directions',
        ),
    ]
