# Generated by Django 3.2.4 on 2021-07-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_journey_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='route',
        ),
        migrations.AddField(
            model_name='stopinfo',
            name='weight',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Routable')], default=1),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lat',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lon',
            field=models.CharField(max_length=11),
        ),
    ]
