# Generated by Django 3.2.4 on 2021-07-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_journey_directions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='directions',
        ),
    ]
