# Generated by Django 3.2.4 on 2021-07-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_journey_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='directions',
            field=models.JSONField(default=''),
        ),
    ]
