# Generated by Django 3.2.4 on 2021-07-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_feedback_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='from_location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='to_location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
