# Generated by Django 3.2.4 on 2021-07-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_journey_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopinfo',
            name='weight',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Routable')], default=1),
        ),
    ]
