# Generated by Django 3.2.4 on 2021-07-16 03:45

import api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210715_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='fee',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='first_stripe',
            field=models.CharField(choices=[('#EEEEEE', 'WHITE'), ('#9E9E9E', 'BLACK'), ('#EF5350', 'RED'), ('#42a5f5', 'BLUE'), ('#9CCC65', 'GREEN'), ('#1B5E20', 'DEEP_GREEN'), ('#FDD835', 'YELLOW'), ('#a1887f', 'BROWN')], default=api.enums.RouteColors['WHITE'], max_length=9),
        ),
        migrations.AlterField(
            model_name='route',
            name='last_stripe',
            field=models.CharField(choices=[('#EEEEEE', 'WHITE'), ('#9E9E9E', 'BLACK'), ('#EF5350', 'RED'), ('#42a5f5', 'BLUE'), ('#9CCC65', 'GREEN'), ('#1B5E20', 'DEEP_GREEN'), ('#FDD835', 'YELLOW'), ('#a1887f', 'BROWN')], default=api.enums.RouteColors['WHITE'], max_length=9),
        ),
    ]
