# Generated by Django 3.2.4 on 2021-07-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210716_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='final_cost',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='journey',
            name='start_cost',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
