# Generated by Django 3.2.4 on 2021-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210716_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='fixed_fee',
            field=models.BooleanField(default=False),
        ),
    ]
